#!/bin/bash

#Command line functions
help() {
	echo $'dir_build [options] <lab> or  dir_build <options>\n

	Options list:\n
	-h  			this page\n
	-t			Create a lab directory within /THM\n 
	-b			Creates a lab directory within /HTB\n
	-p			Creates a lab directory within /swigger\n
	-e			Creates a directory within /exam for when you are sitting practical assessments\n
	-w			Creates directories within /work for your current engagement. This includes a folder for Burp, Nessus and NMAP.\n';

}

version() {
	echo $'version 1.1\nBuilt by Daniel Roberts';
}

base=~/Share;

base() {
 	case $flag in
 		-t) base=$base/THM/$lab;;
		-b) base=$base/HTB/$lab;;
		-e) base=$base/exam/$lab;;
		-w) base=$base/work/$lab;;
		-p) base=$base/swigger/$lab;;
	esac

	echo $build $base;
}

build(){
	mkdir -p $1;
}

#Positional Parameters
flag=$1;
lab=$2;



if [[ $OPTIND -eq 1 ]] && [[ -z $flag  ]]; then echo "No options were passed";
	shift $((OPTIND-1));
	exit;
else
	#Command line arguments
	while getopts ":ht:b:ve:w:" option; do
		case $option in
		#THM, HTB, Exam or Work
		t | b | e | w | p) base $flag $lab;; 
		h) help
		   exit;;
		v) version
		   exit;;
		\?) echo "Invalid Option";
			help
			exit;;
		esac

		/bin/clear;

		if [[ $flag = "-w" ]]; 
		then
			build $base/nmap
			build $base/burp
			
			##Source burp script and create file
			source burper $base $lab
			
			build $base/nessus
			build $base/other
		fi
		echo $base;
		cd $base;
		$SHELL;
	done
fi
