#!/bin/bash

#Command line functions
help() {
	echo $'dir_build [options] <lab> or  dir_build <options>\n

	Options list:\n
	-h  			this page\n
	-t			Create a lab directory within /THM\n 
	-b			Creates a lab directory within /HTB\n
	-p			Creates a lab directory within /swigger\n
	-e			Creates a directory within /exam for when you are sitting practical assessments\n
	-w			Creates directories within /work for your current engagement. This includes a folder for Burp, Nessus and NMAP.\n';

}

version() {
	echo $'version 1.1\nBuilt by Daniel Roberts';
}

base=~/Share;

build() {
 	case $flag in
 		-t) echo $base/THM/$lab;;
		-b) echo $base/HTB/$lab;;
		-e) echo $base/exam/$lab;;
		-w) echo $base/work/$lab;;
		-p) echo $base/swigger/$lab;;
	esac
}

#Positional Parameters
flag=$1;
lab=$2;



if [[ $OPTIND -eq 1 ]] && [[ -z $flag  ]]; then echo "No options were passed";
	shift $((OPTIND-1));
	exit;
else
	#Command line arguments
	while getopts ":ht:b:ve:w:" option; do
		case $option in
		#THM, HTB, Exam or Work
		t | b | e | w | p) build $flag $lab;; 
		h) help
		   exit;;
		v) version
		   exit;;
		\?) echo "Invalid Option";
			help
			exit;;
		esac

		dir=$(build);
		/bin/clear;
		/bin/mkdir -p $dir;
		if [[ $flag = "-w" ]]; 
		then
			/bin/mkdir $dir/nmap
			/bin/mkdir $dir/burp
			
			##Source burp script and create file
			source burper
			create_file $dir $lab
			
			/bin/mkdir $dir/nessus
			/bin/mkdir $dir/other
		fi
		echo $dir;
		cd $dir;
		$SHELL;
	done
fi
