package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// resolveScope loads scope.txt if it exists, or runs the interactive scope
// review to derive and optionally edit an implicit scope from engage_jr data.
// The result is always saved to scope.txt so future runs skip the review.
func resolveScope(engDir, cliScope string, engMeta EngagementMeta, allHosts []string) (*Scope, error) {
	scopePath := findScopeFile(engDir, cliScope)

	if scopePath != "" {
		scope, err := loadScope(scopePath)
		if err != nil {
			return nil, fmt.Errorf("loading scope file %s: %w", scopePath, err)
		}
		logDebug("scope loaded from %s", scopePath)
		return scope, nil
	}

	logInfo("no scope.txt found — running scope review")
	return reviewAndSaveScope(engDir, engMeta, allHosts)
}

// reviewAndSaveScope presents the implicit scope to the user, shows the
// engage_jr context it was derived from, and offers to edit before saving.
func reviewAndSaveScope(engDir string, engMeta EngagementMeta, allHosts []string) (*Scope, error) {
	content := buildImplicitScopeContent(engMeta, allHosts)

	printScopeReview(engMeta, content)

	fmt.Print("Edit scope before proceeding? [y/N]: ")
	answer := strings.ToLower(strings.TrimSpace(readLine()))
	if answer == "y" || answer == "yes" {
		edited, err := openEditorWithContent(content)
		if err != nil {
			logWarn("editor failed: %v — using derived scope", err)
		} else {
			content = edited
		}
	}

	scope, err := buildScopeFromContent(content)
	if err != nil {
		return nil, fmt.Errorf("invalid scope after editing: %w", err)
	}

	if !dryRun {
		scopePath := filepath.Join(engDir, "scope.txt")
		if err := os.WriteFile(scopePath, []byte(content), 0644); err != nil {
			logWarn("could not save scope.txt: %v — scope applies this run only", err)
		} else {
			logInfo("scope saved to %s", scopePath)
		}
	}

	return scope, nil
}

// printScopeReview prints the engage_jr context and derived scope for the user
// to review before optionally editing.
func printScopeReview(engMeta EngagementMeta, scopeContent string) {
	fmt.Printf("\n=== Scope Review — %s ===\n\n", engMeta.Name)

	// Structured data from engage_jr
	if engMeta.Mode != "" {
		fmt.Printf("  Mode      : %s\n", engMeta.Mode)
	}
	if engMeta.SSHHost != "" {
		fmt.Printf("  SSH host  : %s\n", engMeta.SSHHost)
	}
	if engMeta.HostCount > 0 {
		fmt.Printf("  Hosts     : %d (%d with HTTP/S)\n", engMeta.HostCount, engMeta.HTTPCount)
	}

	// Individual targets from engage_jr env (TARGET_1, TARGET_2, ...)
	if len(engMeta.Env) > 0 {
		var targetKeys []string
		for k := range engMeta.Env {
			if strings.HasPrefix(k, "TARGET_") && k != "TARGETS" {
				targetKeys = append(targetKeys, k)
			}
		}
		sort.Strings(targetKeys)
		if len(targetKeys) > 0 {
			fmt.Printf("\n  Targets from engage_jr session:\n")
			for _, k := range targetKeys {
				fmt.Printf("    %-16s %s\n", k, engMeta.Env[k])
			}
		}
		if v := engMeta.Env["HTTP_TARGETS"]; v != "" {
			fmt.Printf("\n  HTTP targets : %s\n", v)
		}
	}

	// Derived scope entries (non-comment lines)
	fmt.Printf("\n  Derived scope entries:\n")
	for _, line := range strings.Split(strings.TrimSpace(scopeContent), "\n") {
		line = strings.TrimSpace(line)
		if line != "" && !strings.HasPrefix(line, "#") {
			fmt.Printf("    %s\n", line)
		}
	}
	fmt.Println()
}

// buildImplicitScopeContent generates the initial scope file content from
// engage_jr metadata and the current host lists.
func buildImplicitScopeContent(engMeta EngagementMeta, allHosts []string) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Scope for engagement: %s (mode: %s)\n", engMeta.Name, engMeta.Mode)
	fmt.Fprintf(&b, "# Generated by recon_jr from engage_jr host file\n")
	fmt.Fprintf(&b, "#\n")
	fmt.Fprintf(&b, "# Supported formats:\n")
	fmt.Fprintf(&b, "#   hostname       example.com      (matches *.example.com too)\n")
	fmt.Fprintf(&b, "#   IP             10.10.10.50\n")
	fmt.Fprintf(&b, "#   CIDR           10.10.10.0/24\n")
	fmt.Fprintf(&b, "#   IP range       10.10.10.1-20\n")
	fmt.Fprintf(&b, "#   URL            https://example.com  (scheme stripped)\n")
	fmt.Fprintf(&b, "#\n")

	// Use engage_jr's structured Targets if available (they're already deduped)
	if len(engMeta.Targets) > 0 {
		fmt.Fprintf(&b, "# From engage_jr Targets\n")
		for _, t := range engMeta.Targets {
			fmt.Fprintln(&b, t)
		}
	} else {
		// Fall back to the host file entries
		fmt.Fprintf(&b, "# From host file\n")
		seen := make(map[string]struct{})
		for _, h := range allHosts {
			if _, ok := seen[h]; !ok {
				seen[h] = struct{}{}
				fmt.Fprintln(&b, h)
			}
		}
	}

	fmt.Fprintf(&b, "\n# To enable subdomain enumeration across the full root domain, add it explicitly:\n")
	fmt.Fprintf(&b, "# e.g. add 'erebus.cymru' to scan all subdomains, not just the targets above\n")

	return b.String()
}

// buildScopeFromContent parses scope file content (as a string) into a Scope.
func buildScopeFromContent(content string) (*Scope, error) {
	s := &Scope{ips: make(map[string]struct{})}
	var nonEmpty int
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		nonEmpty++
		if err := s.addEntry(line); err != nil {
			logWarn("scope: skipping %q: %v", line, err)
		}
	}
	if nonEmpty == 0 {
		return nil, fmt.Errorf("scope is empty after removing comments")
	}
	return s, nil
}

// openEditorWithContent writes content to a temp file, opens the user's
// preferred editor ($EDITOR → $VISUAL → nano → vi), and returns the edited
// content. Returns the original content unchanged if no editor is available.
func openEditorWithContent(content string) (string, error) {
	editor := resolveEditor()
	if editor == "" {
		return content, fmt.Errorf("no editor found — set $EDITOR environment variable")
	}

	tmp, err := os.CreateTemp("", "recon_jr_scope_*.txt")
	if err != nil {
		return content, fmt.Errorf("creating temp file: %w", err)
	}
	defer os.Remove(tmp.Name())

	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return content, fmt.Errorf("writing temp file: %w", err)
	}
	tmp.Close()

	cmd := exec.Command(editor, tmp.Name())
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return content, fmt.Errorf("editor %s exited: %w", editor, err)
	}

	data, err := os.ReadFile(tmp.Name())
	if err != nil {
		return content, fmt.Errorf("reading edited file: %w", err)
	}
	return string(data), nil
}

// reviewAndSaveWebScope offers an interactive prompt to restrict web application
// testing to a subset of the in-scope hosts. Called when no web_scope.txt
// exists. inScopeHosts is the list that passed the main scope filter — those
// are pre-filled in the editor so the user can remove hosts they don't want
// web-tested. Returns nil (no error) if the user declines, meaning web testing
// will fall back to the main scope.
func reviewAndSaveWebScope(engDir string, inScopeHosts []string) (*Scope, error) {
	fmt.Println()
	fmt.Println("=== Web Test Scope ===")
	fmt.Println()
	fmt.Println("  The main scope controls enumeration and infrastructure scanning (nmap etc.).")
	fmt.Println("  A separate web test scope lets you restrict web app testing (nuclei,")
	fmt.Println("  feroxbuster, nikto, etc.) to a subset of those hosts.")
	fmt.Println()
	fmt.Printf("  In-scope hosts available for web testing: %d\n", len(inScopeHosts))
	preview := inScopeHosts
	if len(preview) > 8 {
		preview = preview[:8]
	}
	for _, h := range preview {
		fmt.Printf("    %s\n", h)
	}
	if len(inScopeHosts) > 8 {
		fmt.Printf("    ... and %d more\n", len(inScopeHosts)-8)
	}
	fmt.Println()
	fmt.Print("Restrict web testing to a subset of these hosts? [y/N]: ")

	answer := strings.ToLower(strings.TrimSpace(readLine()))
	if answer != "y" && answer != "yes" {
		logInfo("web scope: not restricted — web testing targets all in-scope hosts")
		return nil, nil
	}

	// Pre-fill with all in-scope hosts so the user can delete what they don't want
	var b strings.Builder
	fmt.Fprintf(&b, "# Web test scope for this engagement\n")
	fmt.Fprintf(&b, "# Delete any hosts you do NOT want web-tested.\n")
	fmt.Fprintf(&b, "# Same format as scope.txt: hostname, IP, CIDR, IP range, or URL.\n")
	fmt.Fprintf(&b, "#\n")
	for _, h := range inScopeHosts {
		fmt.Fprintln(&b, h)
	}
	content := b.String()

	edited, err := openEditorWithContent(content)
	if err != nil {
		logWarn("editor failed: %v — web testing will target all in-scope hosts", err)
		return nil, nil
	}
	content = edited

	scope, err := buildScopeFromContent(content)
	if err != nil {
		return nil, fmt.Errorf("invalid web scope after editing: %w", err)
	}

	if !dryRun {
		webScopePath := filepath.Join(engDir, "web_scope.txt")
		if err := os.WriteFile(webScopePath, []byte(content), 0644); err != nil {
			logWarn("could not save web_scope.txt: %v — web scope applies this run only", err)
		} else {
			logInfo("web scope saved to %s", webScopePath)
		}
	}

	return scope, nil
}

// resolveEditor returns the editor binary to use, in preference order:
// $EDITOR → $VISUAL → nano → vi → vim
func resolveEditor() string {
	for _, env := range []string{"EDITOR", "VISUAL"} {
		if v := os.Getenv(env); v != "" {
			return v
		}
	}
	for _, candidate := range []string{"nano", "vi", "vim"} {
		if _, err := exec.LookPath(candidate); err == nil {
			return candidate
		}
	}
	return ""
}
